#ifndef RETURN_VALS_H
#define RETURN_VALS_H

#define INCORRECT_ARG_COUNT			1
#define ERROR_WITH_SELECT			2
#define ERROR_WITH_RECV				3
#define ERROR_RESOLVING_LISTENER	4
#define ERROR_WITH_SOCKET			5
#define ERROR_SETSOCKOPT			6
#define ERROR_WITH_BIND				7
#define ERROR_WITH_CONNECT			8
#define EMPTY_RESPONSE_FROM_SERVER	9
#define ERROR_WITH_SEND				10
#define ERROR_WITH_READ				11

#endif
